"""initial platform modules

Revision ID: b2e33fa9e680
Revises:
Create Date: 2026-07-29 15:56:19.017389
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b2e33fa9e680"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capability_invocations",
        sa.Column("capability_name", sa.String(length=180), nullable=False),
        sa.Column("actor_id", sa.String(length=120), nullable=True),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capability_invocations_actor_id"),
        "capability_invocations",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_invocations_capability_name"),
        "capability_invocations",
        ["capability_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_invocations_status"), "capability_invocations", ["status"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "knowledge_networks",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("branch", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("concept_groups", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", "version"),
    )
    op.create_index(op.f("ix_knowledge_networks_key"), "knowledge_networks", ["key"], unique=False)
    op.create_index(
        op.f("ix_knowledge_networks_project_id"), "knowledge_networks", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_networks_status"), "knowledge_networks", ["status"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id"),
    )
    op.create_index(
        op.f("ix_project_members_project_id"), "project_members", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    op.create_table(
        "secrets",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("encrypted_value", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name"),
    )
    op.create_index(op.f("ix_secrets_project_id"), "secrets", ["project_id"], unique=False)
    op.create_table(
        "catalogs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("connector_type", sa.String(length=64), nullable=False),
        sa.Column("secret_id", sa.String(length=36), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("scope", sa.String(length=24), nullable=False),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["secret_id"], ["secrets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name"),
    )
    op.create_index(
        op.f("ix_catalogs_connector_type"), "catalogs", ["connector_type"], unique=False
    )
    op.create_index(op.f("ix_catalogs_project_id"), "catalogs", ["project_id"], unique=False)
    op.create_index(op.f("ix_catalogs_status"), "catalogs", ["status"], unique=False)
    op.create_table(
        "data_resources",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("catalog_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("discovery_status", sa.String(length=24), nullable=False),
        sa.Column("schema", sa.JSON(), nullable=False),
        sa.Column("governance", sa.JSON(), nullable=False),
        sa.Column("row_estimate", sa.Integer(), nullable=True),
        sa.Column("last_seen_run_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["catalog_id"], ["catalogs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_id", "external_id"),
    )
    op.create_index(
        op.f("ix_data_resources_catalog_id"), "data_resources", ["catalog_id"], unique=False
    )
    op.create_index(
        op.f("ix_data_resources_category"), "data_resources", ["category"], unique=False
    )
    op.create_index(op.f("ix_data_resources_name"), "data_resources", ["name"], unique=False)
    op.create_index(
        op.f("ix_data_resources_project_id"), "data_resources", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_data_resources_status"), "data_resources", ["status"], unique=False)
    op.create_table(
        "discovery_runs",
        sa.Column("catalog_id", sa.String(length=36), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("statistics", sa.JSON(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["catalog_id"], ["catalogs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_runs_catalog_id"), "discovery_runs", ["catalog_id"], unique=False
    )
    op.create_index(op.f("ix_discovery_runs_status"), "discovery_runs", ["status"], unique=False)
    op.create_table(
        "object_types",
        sa.Column("network_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("concept_group", sa.String(length=100), nullable=True),
        sa.Column("source_resource_id", sa.String(length=36), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("primary_keys", sa.JSON(), nullable=False),
        sa.Column("display_key", sa.String(length=100), nullable=True),
        sa.Column("incremental_key", sa.String(length=100), nullable=True),
        sa.Column("indexes", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["network_id"], ["knowledge_networks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_resource_id"], ["data_resources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("network_id", "key"),
    )
    op.create_index(
        op.f("ix_object_types_network_id"), "object_types", ["network_id"], unique=False
    )
    op.create_table(
        "action_types",
        sa.Column("network_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("operation", sa.String(length=24), nullable=False),
        sa.Column("object_type_id", sa.String(length=36), nullable=False),
        sa.Column("condition", sa.JSON(), nullable=False),
        sa.Column("impact_contract", sa.JSON(), nullable=False),
        sa.Column("parameters_schema", sa.JSON(), nullable=False),
        sa.Column("executor", sa.JSON(), nullable=False),
        sa.Column("permission", sa.String(length=24), nullable=False),
        sa.Column("retry_policy", sa.JSON(), nullable=False),
        sa.Column("compensation", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["network_id"], ["knowledge_networks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["object_type_id"], ["object_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("network_id", "key"),
    )
    op.create_index(
        op.f("ix_action_types_network_id"), "action_types", ["network_id"], unique=False
    )
    op.create_table(
        "relation_types",
        sa.Column("network_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_object_type_id", sa.String(length=36), nullable=False),
        sa.Column("target_object_type_id", sa.String(length=36), nullable=False),
        sa.Column("cardinality", sa.String(length=32), nullable=False),
        sa.Column("mapping_type", sa.String(length=40), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["network_id"], ["knowledge_networks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_object_type_id"], ["object_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_object_type_id"], ["object_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("network_id", "key"),
    )
    op.create_index(
        op.f("ix_relation_types_network_id"), "relation_types", ["network_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relation_types_network_id"), table_name="relation_types")
    op.drop_table("relation_types")
    op.drop_index(op.f("ix_action_types_network_id"), table_name="action_types")
    op.drop_table("action_types")
    op.drop_index(op.f("ix_object_types_network_id"), table_name="object_types")
    op.drop_table("object_types")
    op.drop_index(op.f("ix_discovery_runs_status"), table_name="discovery_runs")
    op.drop_index(op.f("ix_discovery_runs_catalog_id"), table_name="discovery_runs")
    op.drop_table("discovery_runs")
    op.drop_index(op.f("ix_data_resources_status"), table_name="data_resources")
    op.drop_index(op.f("ix_data_resources_project_id"), table_name="data_resources")
    op.drop_index(op.f("ix_data_resources_name"), table_name="data_resources")
    op.drop_index(op.f("ix_data_resources_category"), table_name="data_resources")
    op.drop_index(op.f("ix_data_resources_catalog_id"), table_name="data_resources")
    op.drop_table("data_resources")
    op.drop_index(op.f("ix_catalogs_status"), table_name="catalogs")
    op.drop_index(op.f("ix_catalogs_project_id"), table_name="catalogs")
    op.drop_index(op.f("ix_catalogs_connector_type"), table_name="catalogs")
    op.drop_table("catalogs")
    op.drop_index(op.f("ix_secrets_project_id"), table_name="secrets")
    op.drop_table("secrets")
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_knowledge_networks_status"), table_name="knowledge_networks")
    op.drop_index(op.f("ix_knowledge_networks_project_id"), table_name="knowledge_networks")
    op.drop_index(op.f("ix_knowledge_networks_key"), table_name="knowledge_networks")
    op.drop_table("knowledge_networks")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_capability_invocations_status"), table_name="capability_invocations")
    op.drop_index(
        op.f("ix_capability_invocations_capability_name"), table_name="capability_invocations"
    )
    op.drop_index(op.f("ix_capability_invocations_actor_id"), table_name="capability_invocations")
    op.drop_table("capability_invocations")
    # ### end Alembic commands ###
